baseURL: https://mariashaikh.com
languageCode: en-us
title:  "Maria Shaikh's Website"
theme: "dimension"

languages:
  en:
    languageName: English
    weight: 1


# Enable Google Analytics
googleAnalytics: UA-122321624-2

# Enable global emoji support
enableEmoji: true
